### ISSUE TITLE
When running aggregateMember I get NPE on okhttp

### ISSUE THREAD

**Issue by calendarbudget** [mxenabled/mx-platform-java#70]
Whever I run 
`apiInstance.aggregateMember(memberGuid, userGuid)`
I get a NullPointerException as follows. I saw some chatter on another project for the same issue about updating the OpenAPI version, but haven't been able to resolve it.
Here's the stacktrace.

```
java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.MediaType$Companion.parse, parameter <this>
	at okhttp3.MediaType$Companion.parse(MediaType.kt)
	at okhttp3.MediaType.parse(MediaType.kt)
	at com.mx.client.ApiClient.buildRequest(ApiClient.java:1131)
	at com.mx.client.ApiClient.buildCall(ApiClient.java:1087)
	at com.mx.client.mx_platform_api.MxPlatformApi.aggregateMemberCall(MxPlatformApi.java:198)
	at com.mx.client.mx_platform_api.MxPlatformApi.aggregateMemberValidateBeforeCall(MxPlatformApi.java:215)
	at com.mx.client.mx_platform_api.MxPlatformApi.aggregateMemberWithHttpInfo(MxPlatformApi.java:252)
	at com.mx.client.mx_platform_api.MxPlatformApi.aggregateMember(MxPlatformApi.java:234)
```

**Comment by calendarbudget** [comment]
Resolved by adding the following to ApiClient.java (at line 1131)

```
if (contentType==null) {
      contentType = "application/json";
  }
```
